name: build

on:
  pull_request:
   branches:
   -master
  push:
   branches:
   -master

jobs:
  xgo:
    strategy:
      matrix:
        go_version:
          - 1.12.4
          - 1.13.x
    runs-on: ubuntu-latest
    steps:
      -
        name: Build with xgo
        uses: crazy-max/ghaction-xgo@v0.1.0
        with:
          go_version: ${{ matrix.go_version }}
          targets: windows/386,windows/amd64,linux/386,linux/amd64,darwin/386,darwin/amd64
          out: build/pinbak
          v: true
          x: false
          ldflags: -s -w
      -
        name: Check output
        run: |
          file build/*
